### ISSUE TITLE
Ensure TypeScript builds without errors

### ISSUE THREAD

**Issue by kibertoad** [kibertoad/unzipomatic#11]
First quick conversion wasn't perfect, it still doesn't compile.

At this stage it's fine to use `any` and `ts-ignore`, we can cleanup in a next step.

**Comment by kibertoad** [comment]
@metcoder95 @H4ad anyone wants to pick it up today? if no, I'll have some time for it tomorrow.

**Comment by H4ad** [comment]
I will only have time tomorrow, let me know when you start, maybe I could get something fixed before you start.

**Comment by kibertoad** [comment]
@H4ad planning to start in an hour or so, can either work on refining public API, or fixing TS. How does your timeline look like today?

**Comment by metcoder95** [comment]
Sorry, has been having a busy weekend; feel free to pick it from my side, I'll focus on the other task assigned to me through the day 👍

**Comment by H4ad** [comment]
@kibertoad focus on the design the of the API, I can fix the TS issues.

**Comment by kibertoad** [comment]
@H4ad Ok!
