### ISSUE TITLE
Port fd-slicer

### ISSUE THREAD

**Issue by H4ad** [kibertoad/unzipomatic#13]
Because of https://github.com/andrewrk/node-fd-slicer/pull/5

**Comment by kibertoad** [comment]
@H4ad @metcoder95 Should we inline the library inside this repo, or publish `@unzipomatic/fd-slicer`?

**Comment by H4ad** [comment]
It's very downloaded too, so I think that worth to fork and publish a new version, also, I don't think we should put under organization and publish as a independent library

**Comment by kibertoad** [comment]
@H4ad How can we avoid name clash then, if there is no organizational prefix? Rename to something like fd-sliceomatic :D?

**Comment by H4ad** [comment]
Yes, or "better-fs-slicer", something like that.

**Comment by kibertoad** [comment]
I would start by forking it, and change what makes sense

**Comment by kibertoad** [comment]
@H4ad Done: https://github.com/kibertoad/better-fd-slicer
