### ISSUE TITLE
Inline buffer-crc32 to avoid deprecations

### ISSUE THREAD

**Issue by kibertoad** [kibertoad/unzipomatic#16]
https://github.com/brianloveswords/buffer-crc32/blob/master/index.js uses deprecated Buffer API. Inlining entire library (it is tiny) might be the easiest fix for it.

Let's see if author reacts to https://github.com/brianloveswords/buffer-crc32/issues/20, though

**Comment by H4ad** [comment]
Should we migrate to https://www.npmjs.com/package/@node-rs/crc32 or keep this one?

**Comment by kibertoad** [comment]
@H4ad I've created separate ticket for migration, but it is not critical for the first release.
buffer-crc32 author merged all of my PRs, so short-term we are good.
