### ISSUE TITLE
Refactor the code to TypeScript

### ISSUE THREAD

**Issue by H4ad** [kibertoad/unzipomatic#5]
We can organize/synchronize who will be responsible for doing the initial refactor, we can post the updates and organize them in this issue.

Initially, I think we just need to modernize the code by introducing class and avoiding prototypes, and then migrate all files to TypeScript and split that huge file to multiple files.

Then, after this initial refactor, we can start work on the new API.

**Comment by kibertoad** [comment]
@H4ad I'm doing the slicing and surface-level conversion to TS right now, will use it as a basis when coming up with a new API
