### ISSUE TITLE
Migrate tests to vitest

### ISSUE THREAD

**Issue by H4ad** [kibertoad/unzipomatic#6]
This is something we can do in parallel to #5, we can modernize the tests and use `vitest` to be easier to work on and add more tests.

**Comment by kibertoad** [comment]
This is probably currently blocked by https://github.com/kibertoad/unzipomatic/issues/4

**Comment by H4ad** [comment]
Not exactly, it we do in the following order:

- transpile the code to ts
- rewrite the tests to vitest
- then rewrite the previous code to new design

Then we will be able to do it in parallel.

I suggested this way instead of starting the rewriting using the new design because none of us are familiar with the code of that library and the easiest way to understand is just to transpile to typescript while maintaining the same functionality/design.

But I'm not against starting the lib already in the new design.

**Comment by kibertoad** [comment]
@H4ad Fair point. Can you pick this one up after we merge https://github.com/kibertoad/unzipomatic/pull/10
?
converting just few tests to ensure our code still runs correctly would be very valuable

**Comment by H4ad** [comment]
Sure!

**Comment by H4ad** [comment]
This is basically solved now.
